name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure Core RDP Settings
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
                             -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "SecurityLayer" -Value 0 -Force

          netsh advfirewall firewall delete rule name="RDP-Tailscale" | Out-Null
          netsh advfirewall firewall add rule name="RDP-Tailscale" `
            dir=in action=allow protocol=TCP localport=3389 | Out-Null

          Restart-Service -Name TermService -Force

      - name: Install Tailscale
        shell: powershell
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath -UseBasicParsing
          Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
          Remove-Item $installerPath -Force

      - name: Create RDP User, Start Tailscale and Send All Details to Telegram
        shell: powershell
        run: |
          # --- Generate secure random password ---
          $charSet = @{
              Upper   = [char[]](65..90)
              Lower   = [char[]](97..122)
              Number  = [char[]](48..57)
              Special = ([char[]](33..47) + [char[]](58..64) + [char[]](91..96) + [char[]](123..126))
          }
          $rawPassword = @()
          $rawPassword += $charSet.Upper | Get-Random -Count 4
          $rawPassword += $charSet.Lower | Get-Random -Count 4
          $rawPassword += $charSet.Number | Get-Random -Count 4
          $rawPassword += $charSet.Special | Get-Random -Count 4
          $password = -join ($rawPassword | Sort-Object { Get-Random })

          # --- Create or update local user "RDP" ---
          if (Get-LocalUser -Name "RDP" -ErrorAction SilentlyContinue) {
              $securePass = ConvertTo-SecureString $password -AsPlainText -Force
              Set-LocalUser -Name "RDP" -Password $securePass
          } else {
              $securePass = ConvertTo-SecureString $password -AsPlainText -Force
              New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
          }

          Add-LocalGroupMember -Group "Administrators" -Member "RDP" -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP" -ErrorAction SilentlyContinue

          if (-not (Get-LocalUser -Name "RDP" -ErrorAction SilentlyContinue)) {
              Write-Error "User creation failed"
              exit 1
          }

          # --- Ensure tailscale binary exists ---
          $tsExe = Join-Path $env:ProgramFiles "Tailscale\tailscale.exe"
          if (-not (Test-Path $tsExe)) {
              Write-Error "tailscale.exe not found at $tsExe - make sure the Install Tailscale step succeeded"
              exit 1
          }

          # --- Start Tailscale with auth key from repo secrets ---
          & $tsExe up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname="gh-runner-$env:GITHUB_RUN_ID" | Out-Null

          # --- Wait for Tailscale IPv4 address ---
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 20) {
              Start-Sleep -Seconds 5
              $tsIP = & $tsExe ip -4
              if ($tsIP) { $tsIP = $tsIP.Trim() }
              $retries++
          }

          if (-not $tsIP) {
              Write-Error "Tailscale IP not assigned after waiting. Exiting."
              exit 1
          }

          # Save IP to env for later steps
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV

          # --- Send single Telegram message with all details ---
          $botToken = "8192557129:AAGi9SQI0_4-skSEaNMxyCIEsRfp3NkPSEw"
          $chatId = "7646847122"

          $message = @"
[ 🔒 RDP ACCESS ]
• Address: $tsIP
• Username: RDP
• Password: $password

👉 Connect via Tailscale. Keep creds private.
"@

          $body = @{ chat_id = $chatId; text = $message }
          try {
              Invoke-RestMethod -Uri "https://api.telegram.org/bot$botToken/sendMessage" -Method Post -Body $body -ErrorAction Stop | Out-Null
          } catch {
              Write-Error "Failed to send Telegram message: $($_.Exception.Message)"
              exit 1
          }

      - name: Verify RDP Accessibility
        shell: powershell
        run: |
          $ip = $env:TAILSCALE_IP
          Write-Host "Testing RDP connectivity to $ip:3389"
          $testResult = Test-NetConnection -ComputerName $ip -Port 3389 -WarningAction SilentlyContinue
          if (-not $testResult.TcpTestSucceeded) {
              Write-Error "TCP connection to RDP port 3389 failed"
              exit 1
          }
          Write-Host "TCP connectivity successful!"

      - name: Maintain Connection
        shell: powershell
        run: |
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "Address: $env:TAILSCALE_IP"
          Write-Host "Username: RDP"
          Write-Host "Password: (sent to Telegram)"
          Write-Host "==================`n"
          while ($true) {
              Write-Host "[$(Get-Date)] RDP Active - Use Cancel workflow in GitHub Actions to stop"
              Start-Sleep -Seconds 300
          }
